/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckRouteImport } from './routes/check'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminEmergencyRouteImport } from './routes/admin/emergency'
import { Route as AdminFacultyRouteImport } from './routes/admin/faculty'
import { Route as AdminMovementPassesRouteImport } from './routes/admin/movement-passes'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminSafetyAnalyticsRouteImport } from './routes/admin/safety-analytics'
import { Route as AdminSafetyPreventionRouteImport } from './routes/admin/safety-prevention'
import { Route as AdminSafetyReportsRouteImport } from './routes/admin/safety-reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminTimetableRouteImport } from './routes/admin/timetable'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminViolationsRouteImport } from './routes/admin/violations'
import { Route as FacultyCheckRouteImport } from './routes/faculty/check'
import { Route as FacultyDashboardRouteImport } from './routes/faculty/dashboard'
import { Route as FacultyNotificationsRouteImport } from './routes/faculty/notifications'
import { Route as FacultyPassesRouteImport } from './routes/faculty/passes'
import { Route as FacultyReportsRouteImport } from './routes/faculty/reports'
import { Route as FacultySettingsRouteImport } from './routes/faculty/settings'
import { Route as FacultyTimetableRouteImport } from './routes/faculty/timetable'
import { Route as HodCasesRouteImport } from './routes/hod/cases'
import { Route as HodDashboardRouteImport } from './routes/hod/dashboard'
import { Route as HodDepartmentRouteImport } from './routes/hod/department'
import { Route as HodNotificationsRouteImport } from './routes/hod/notifications'
import { Route as HodPassesRouteImport } from './routes/hod/passes'
import { Route as HodSafetyAnalyticsRouteImport } from './routes/hod/safety-analytics'
import { Route as HodSafetyPreventionRouteImport } from './routes/hod/safety-prevention'
import { Route as HodSettingsRouteImport } from './routes/hod/settings'
import { Route as HodStudentsRouteImport } from './routes/hod/students'
import { Route as HodTimetableRouteImport } from './routes/hod/timetable'
import { Route as HodViolationsRouteImport } from './routes/hod/violations'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as SecurityCheckRouteImport } from './routes/security/check'
import { Route as SecurityDashboardRouteImport } from './routes/security/dashboard'
import { Route as SecurityIncidentsRouteImport } from './routes/security/incidents'
import { Route as SecurityNotificationsRouteImport } from './routes/security/notifications'
import { Route as SecurityPassesRouteImport } from './routes/security/passes'
import { Route as SecurityProfileRouteImport } from './routes/security/profile'
import { Route as SecurityReportsRouteImport } from './routes/security/reports'
import { Route as SecuritySettingsRouteImport } from './routes/security/settings'
import { Route as SecurityTimetableRouteImport } from './routes/security/timetable'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentExplanationsRouteImport } from './routes/student/explanations'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentPassesRouteImport } from './routes/student/passes'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentTimetableRouteImport } from './routes/student/timetable'
import { Route as StudentViolationsRouteImport } from './routes/student/violations'
import { Route as AdminReportsReportIdRouteImport } from './routes/admin/reports.$reportId'
import { Route as HodCasesReportIdRouteImport } from './routes/hod/cases.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmergencyRoute = AdminEmergencyRouteImport.update({
  id: '/admin/emergency',
  path: '/admin/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/admin/faculty',
  path: '/admin/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMovementPassesRoute = AdminMovementPassesRouteImport.update({
  id: '/admin/movement-passes',
  path: '/admin/movement-passes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSafetyAnalyticsRoute = AdminSafetyAnalyticsRouteImport.update({
  id: '/admin/safety-analytics',
  path: '/admin/safety-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSafetyPreventionRoute = AdminSafetyPreventionRouteImport.update({
  id: '/admin/safety-prevention',
  path: '/admin/safety-prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSafetyReportsRoute = AdminSafetyReportsRouteImport.update({
  id: '/admin/safety-reports',
  path: '/admin/safety-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViolationsRoute = AdminViolationsRouteImport.update({
  id: '/admin/violations',
  path: '/admin/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCheckRoute = FacultyCheckRouteImport.update({
  id: '/faculty/check',
  path: '/faculty/check',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyNotificationsRoute = FacultyNotificationsRouteImport.update({
  id: '/faculty/notifications',
  path: '/faculty/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyPassesRoute = FacultyPassesRouteImport.update({
  id: '/faculty/passes',
  path: '/faculty/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyReportsRoute = FacultyReportsRouteImport.update({
  id: '/faculty/reports',
  path: '/faculty/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySettingsRoute = FacultySettingsRouteImport.update({
  id: '/faculty/settings',
  path: '/faculty/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyTimetableRoute = FacultyTimetableRouteImport.update({
  id: '/faculty/timetable',
  path: '/faculty/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const HodCasesRoute = HodCasesRouteImport.update({
  id: '/hod/cases',
  path: '/hod/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const HodDashboardRoute = HodDashboardRouteImport.update({
  id: '/hod/dashboard',
  path: '/hod/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HodDepartmentRoute = HodDepartmentRouteImport.update({
  id: '/hod/department',
  path: '/hod/department',
  getParentRoute: () => rootRouteImport,
} as any)
const HodNotificationsRoute = HodNotificationsRouteImport.update({
  id: '/hod/notifications',
  path: '/hod/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HodPassesRoute = HodPassesRouteImport.update({
  id: '/hod/passes',
  path: '/hod/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const HodSafetyAnalyticsRoute = HodSafetyAnalyticsRouteImport.update({
  id: '/hod/safety-analytics',
  path: '/hod/safety-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const HodSafetyPreventionRoute = HodSafetyPreventionRouteImport.update({
  id: '/hod/safety-prevention',
  path: '/hod/safety-prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const HodSettingsRoute = HodSettingsRouteImport.update({
  id: '/hod/settings',
  path: '/hod/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HodStudentsRoute = HodStudentsRouteImport.update({
  id: '/hod/students',
  path: '/hod/students',
  getParentRoute: () => rootRouteImport,
} as any)
const HodTimetableRoute = HodTimetableRouteImport.update({
  id: '/hod/timetable',
  path: '/hod/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const HodViolationsRoute = HodViolationsRouteImport.update({
  id: '/hod/violations',
  path: '/hod/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckRoute = SecurityCheckRouteImport.update({
  id: '/security/check',
  path: '/security/check',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityDashboardRoute = SecurityDashboardRouteImport.update({
  id: '/security/dashboard',
  path: '/security/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIncidentsRoute = SecurityIncidentsRouteImport.update({
  id: '/security/incidents',
  path: '/security/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityNotificationsRoute = SecurityNotificationsRouteImport.update({
  id: '/security/notifications',
  path: '/security/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPassesRoute = SecurityPassesRouteImport.update({
  id: '/security/passes',
  path: '/security/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityProfileRoute = SecurityProfileRouteImport.update({
  id: '/security/profile',
  path: '/security/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityReportsRoute = SecurityReportsRouteImport.update({
  id: '/security/reports',
  path: '/security/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuritySettingsRoute = SecuritySettingsRouteImport.update({
  id: '/security/settings',
  path: '/security/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityTimetableRoute = SecurityTimetableRouteImport.update({
  id: '/security/timetable',
  path: '/security/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentExplanationsRoute = StudentExplanationsRouteImport.update({
  id: '/student/explanations',
  path: '/student/explanations',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/student/notifications',
  path: '/student/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPassesRoute = StudentPassesRouteImport.update({
  id: '/student/passes',
  path: '/student/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/student/settings',
  path: '/student/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/student/timetable',
  path: '/student/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentViolationsRoute = StudentViolationsRouteImport.update({
  id: '/student/violations',
  path: '/student/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsReportIdRoute = AdminReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AdminReportsRoute,
} as any)
const HodCasesReportIdRoute = HodCasesReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => HodCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/violations': typeof ViolationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/movement-passes': typeof AdminMovementPassesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/safety-analytics': typeof AdminSafetyAnalyticsRoute
  '/admin/safety-prevention': typeof AdminSafetyPreventionRoute
  '/admin/safety-reports': typeof AdminSafetyReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/faculty/check': typeof FacultyCheckRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/passes': typeof FacultyPassesRoute
  '/faculty/reports': typeof FacultyReportsRoute
  '/faculty/settings': typeof FacultySettingsRoute
  '/faculty/timetable': typeof FacultyTimetableRoute
  '/hod/cases': typeof HodCasesRouteWithChildren
  '/hod/dashboard': typeof HodDashboardRoute
  '/hod/department': typeof HodDepartmentRoute
  '/hod/notifications': typeof HodNotificationsRoute
  '/hod/passes': typeof HodPassesRoute
  '/hod/safety-analytics': typeof HodSafetyAnalyticsRoute
  '/hod/safety-prevention': typeof HodSafetyPreventionRoute
  '/hod/settings': typeof HodSettingsRoute
  '/hod/students': typeof HodStudentsRoute
  '/hod/timetable': typeof HodTimetableRoute
  '/hod/violations': typeof HodViolationsRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/security/check': typeof SecurityCheckRoute
  '/security/dashboard': typeof SecurityDashboardRoute
  '/security/incidents': typeof SecurityIncidentsRoute
  '/security/notifications': typeof SecurityNotificationsRoute
  '/security/passes': typeof SecurityPassesRoute
  '/security/profile': typeof SecurityProfileRoute
  '/security/reports': typeof SecurityReportsRoute
  '/security/settings': typeof SecuritySettingsRoute
  '/security/timetable': typeof SecurityTimetableRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/explanations': typeof StudentExplanationsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/passes': typeof StudentPassesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/violations': typeof StudentViolationsRoute
  '/reports/': typeof ReportsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/hod/cases/$reportId': typeof HodCasesReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/violations': typeof ViolationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/movement-passes': typeof AdminMovementPassesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/safety-analytics': typeof AdminSafetyAnalyticsRoute
  '/admin/safety-prevention': typeof AdminSafetyPreventionRoute
  '/admin/safety-reports': typeof AdminSafetyReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/faculty/check': typeof FacultyCheckRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/passes': typeof FacultyPassesRoute
  '/faculty/reports': typeof FacultyReportsRoute
  '/faculty/settings': typeof FacultySettingsRoute
  '/faculty/timetable': typeof FacultyTimetableRoute
  '/hod/cases': typeof HodCasesRouteWithChildren
  '/hod/dashboard': typeof HodDashboardRoute
  '/hod/department': typeof HodDepartmentRoute
  '/hod/notifications': typeof HodNotificationsRoute
  '/hod/passes': typeof HodPassesRoute
  '/hod/safety-analytics': typeof HodSafetyAnalyticsRoute
  '/hod/safety-prevention': typeof HodSafetyPreventionRoute
  '/hod/settings': typeof HodSettingsRoute
  '/hod/students': typeof HodStudentsRoute
  '/hod/timetable': typeof HodTimetableRoute
  '/hod/violations': typeof HodViolationsRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/security/check': typeof SecurityCheckRoute
  '/security/dashboard': typeof SecurityDashboardRoute
  '/security/incidents': typeof SecurityIncidentsRoute
  '/security/notifications': typeof SecurityNotificationsRoute
  '/security/passes': typeof SecurityPassesRoute
  '/security/profile': typeof SecurityProfileRoute
  '/security/reports': typeof SecurityReportsRoute
  '/security/settings': typeof SecuritySettingsRoute
  '/security/timetable': typeof SecurityTimetableRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/explanations': typeof StudentExplanationsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/passes': typeof StudentPassesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/violations': typeof StudentViolationsRoute
  '/reports': typeof ReportsIndexRoute
  '/security': typeof SecurityIndexRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/hod/cases/$reportId': typeof HodCasesReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/violations': typeof ViolationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/movement-passes': typeof AdminMovementPassesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/safety-analytics': typeof AdminSafetyAnalyticsRoute
  '/admin/safety-prevention': typeof AdminSafetyPreventionRoute
  '/admin/safety-reports': typeof AdminSafetyReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/faculty/check': typeof FacultyCheckRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/passes': typeof FacultyPassesRoute
  '/faculty/reports': typeof FacultyReportsRoute
  '/faculty/settings': typeof FacultySettingsRoute
  '/faculty/timetable': typeof FacultyTimetableRoute
  '/hod/cases': typeof HodCasesRouteWithChildren
  '/hod/dashboard': typeof HodDashboardRoute
  '/hod/department': typeof HodDepartmentRoute
  '/hod/notifications': typeof HodNotificationsRoute
  '/hod/passes': typeof HodPassesRoute
  '/hod/safety-analytics': typeof HodSafetyAnalyticsRoute
  '/hod/safety-prevention': typeof HodSafetyPreventionRoute
  '/hod/settings': typeof HodSettingsRoute
  '/hod/students': typeof HodStudentsRoute
  '/hod/timetable': typeof HodTimetableRoute
  '/hod/violations': typeof HodViolationsRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/security/check': typeof SecurityCheckRoute
  '/security/dashboard': typeof SecurityDashboardRoute
  '/security/incidents': typeof SecurityIncidentsRoute
  '/security/notifications': typeof SecurityNotificationsRoute
  '/security/passes': typeof SecurityPassesRoute
  '/security/profile': typeof SecurityProfileRoute
  '/security/reports': typeof SecurityReportsRoute
  '/security/settings': typeof SecuritySettingsRoute
  '/security/timetable': typeof SecurityTimetableRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/explanations': typeof StudentExplanationsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/passes': typeof StudentPassesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/violations': typeof StudentViolationsRoute
  '/reports/': typeof ReportsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/hod/cases/$reportId': typeof HodCasesReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/timetable'
    | '/violations'
    | '/admin/audit-logs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/emergency'
    | '/admin/faculty'
    | '/admin/movement-passes'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/safety-analytics'
    | '/admin/safety-prevention'
    | '/admin/safety-reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/violations'
    | '/faculty/check'
    | '/faculty/dashboard'
    | '/faculty/notifications'
    | '/faculty/passes'
    | '/faculty/reports'
    | '/faculty/settings'
    | '/faculty/timetable'
    | '/hod/cases'
    | '/hod/dashboard'
    | '/hod/department'
    | '/hod/notifications'
    | '/hod/passes'
    | '/hod/safety-analytics'
    | '/hod/safety-prevention'
    | '/hod/settings'
    | '/hod/students'
    | '/hod/timetable'
    | '/hod/violations'
    | '/reports/$reportId'
    | '/security/check'
    | '/security/dashboard'
    | '/security/incidents'
    | '/security/notifications'
    | '/security/passes'
    | '/security/profile'
    | '/security/reports'
    | '/security/settings'
    | '/security/timetable'
    | '/student/dashboard'
    | '/student/explanations'
    | '/student/notifications'
    | '/student/passes'
    | '/student/profile'
    | '/student/settings'
    | '/student/timetable'
    | '/student/violations'
    | '/reports/'
    | '/security/'
    | '/admin/reports/$reportId'
    | '/hod/cases/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/timetable'
    | '/violations'
    | '/admin/audit-logs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/emergency'
    | '/admin/faculty'
    | '/admin/movement-passes'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/safety-analytics'
    | '/admin/safety-prevention'
    | '/admin/safety-reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/violations'
    | '/faculty/check'
    | '/faculty/dashboard'
    | '/faculty/notifications'
    | '/faculty/passes'
    | '/faculty/reports'
    | '/faculty/settings'
    | '/faculty/timetable'
    | '/hod/cases'
    | '/hod/dashboard'
    | '/hod/department'
    | '/hod/notifications'
    | '/hod/passes'
    | '/hod/safety-analytics'
    | '/hod/safety-prevention'
    | '/hod/settings'
    | '/hod/students'
    | '/hod/timetable'
    | '/hod/violations'
    | '/reports/$reportId'
    | '/security/check'
    | '/security/dashboard'
    | '/security/incidents'
    | '/security/notifications'
    | '/security/passes'
    | '/security/profile'
    | '/security/reports'
    | '/security/settings'
    | '/security/timetable'
    | '/student/dashboard'
    | '/student/explanations'
    | '/student/notifications'
    | '/student/passes'
    | '/student/profile'
    | '/student/settings'
    | '/student/timetable'
    | '/student/violations'
    | '/reports'
    | '/security'
    | '/admin/reports/$reportId'
    | '/hod/cases/$reportId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/check'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/timetable'
    | '/violations'
    | '/admin/audit-logs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/emergency'
    | '/admin/faculty'
    | '/admin/movement-passes'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/safety-analytics'
    | '/admin/safety-prevention'
    | '/admin/safety-reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/violations'
    | '/faculty/check'
    | '/faculty/dashboard'
    | '/faculty/notifications'
    | '/faculty/passes'
    | '/faculty/reports'
    | '/faculty/settings'
    | '/faculty/timetable'
    | '/hod/cases'
    | '/hod/dashboard'
    | '/hod/department'
    | '/hod/notifications'
    | '/hod/passes'
    | '/hod/safety-analytics'
    | '/hod/safety-prevention'
    | '/hod/settings'
    | '/hod/students'
    | '/hod/timetable'
    | '/hod/violations'
    | '/reports/$reportId'
    | '/security/check'
    | '/security/dashboard'
    | '/security/incidents'
    | '/security/notifications'
    | '/security/passes'
    | '/security/profile'
    | '/security/reports'
    | '/security/settings'
    | '/security/timetable'
    | '/student/dashboard'
    | '/student/explanations'
    | '/student/notifications'
    | '/student/passes'
    | '/student/profile'
    | '/student/settings'
    | '/student/timetable'
    | '/student/violations'
    | '/reports/'
    | '/security/'
    | '/admin/reports/$reportId'
    | '/hod/cases/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckRoute: typeof CheckRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TimetableRoute: typeof TimetableRoute
  ViolationsRoute: typeof ViolationsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEmergencyRoute: typeof AdminEmergencyRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminMovementPassesRoute: typeof AdminMovementPassesRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminReportsRoute: typeof AdminReportsRouteWithChildren
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSafetyAnalyticsRoute: typeof AdminSafetyAnalyticsRoute
  AdminSafetyPreventionRoute: typeof AdminSafetyPreventionRoute
  AdminSafetyReportsRoute: typeof AdminSafetyReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminViolationsRoute: typeof AdminViolationsRoute
  FacultyCheckRoute: typeof FacultyCheckRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyNotificationsRoute: typeof FacultyNotificationsRoute
  FacultyPassesRoute: typeof FacultyPassesRoute
  FacultyReportsRoute: typeof FacultyReportsRoute
  FacultySettingsRoute: typeof FacultySettingsRoute
  FacultyTimetableRoute: typeof FacultyTimetableRoute
  HodCasesRoute: typeof HodCasesRouteWithChildren
  HodDashboardRoute: typeof HodDashboardRoute
  HodDepartmentRoute: typeof HodDepartmentRoute
  HodNotificationsRoute: typeof HodNotificationsRoute
  HodPassesRoute: typeof HodPassesRoute
  HodSafetyAnalyticsRoute: typeof HodSafetyAnalyticsRoute
  HodSafetyPreventionRoute: typeof HodSafetyPreventionRoute
  HodSettingsRoute: typeof HodSettingsRoute
  HodStudentsRoute: typeof HodStudentsRoute
  HodTimetableRoute: typeof HodTimetableRoute
  HodViolationsRoute: typeof HodViolationsRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  SecurityCheckRoute: typeof SecurityCheckRoute
  SecurityDashboardRoute: typeof SecurityDashboardRoute
  SecurityIncidentsRoute: typeof SecurityIncidentsRoute
  SecurityNotificationsRoute: typeof SecurityNotificationsRoute
  SecurityPassesRoute: typeof SecurityPassesRoute
  SecurityProfileRoute: typeof SecurityProfileRoute
  SecurityReportsRoute: typeof SecurityReportsRoute
  SecuritySettingsRoute: typeof SecuritySettingsRoute
  SecurityTimetableRoute: typeof SecurityTimetableRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExplanationsRoute: typeof StudentExplanationsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentPassesRoute: typeof StudentPassesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentViolationsRoute: typeof StudentViolationsRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emergency': {
      id: '/admin/emergency'
      path: '/admin/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AdminEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/admin/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/movement-passes': {
      id: '/admin/movement-passes'
      path: '/admin/movement-passes'
      fullPath: '/admin/movement-passes'
      preLoaderRoute: typeof AdminMovementPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/safety-analytics': {
      id: '/admin/safety-analytics'
      path: '/admin/safety-analytics'
      fullPath: '/admin/safety-analytics'
      preLoaderRoute: typeof AdminSafetyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/safety-prevention': {
      id: '/admin/safety-prevention'
      path: '/admin/safety-prevention'
      fullPath: '/admin/safety-prevention'
      preLoaderRoute: typeof AdminSafetyPreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/safety-reports': {
      id: '/admin/safety-reports'
      path: '/admin/safety-reports'
      fullPath: '/admin/safety-reports'
      preLoaderRoute: typeof AdminSafetyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/violations': {
      id: '/admin/violations'
      path: '/admin/violations'
      fullPath: '/admin/violations'
      preLoaderRoute: typeof AdminViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/check': {
      id: '/faculty/check'
      path: '/faculty/check'
      fullPath: '/faculty/check'
      preLoaderRoute: typeof FacultyCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/notifications': {
      id: '/faculty/notifications'
      path: '/faculty/notifications'
      fullPath: '/faculty/notifications'
      preLoaderRoute: typeof FacultyNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/passes': {
      id: '/faculty/passes'
      path: '/faculty/passes'
      fullPath: '/faculty/passes'
      preLoaderRoute: typeof FacultyPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/reports': {
      id: '/faculty/reports'
      path: '/faculty/reports'
      fullPath: '/faculty/reports'
      preLoaderRoute: typeof FacultyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/settings': {
      id: '/faculty/settings'
      path: '/faculty/settings'
      fullPath: '/faculty/settings'
      preLoaderRoute: typeof FacultySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/timetable': {
      id: '/faculty/timetable'
      path: '/faculty/timetable'
      fullPath: '/faculty/timetable'
      preLoaderRoute: typeof FacultyTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/cases': {
      id: '/hod/cases'
      path: '/hod/cases'
      fullPath: '/hod/cases'
      preLoaderRoute: typeof HodCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/dashboard': {
      id: '/hod/dashboard'
      path: '/hod/dashboard'
      fullPath: '/hod/dashboard'
      preLoaderRoute: typeof HodDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/department': {
      id: '/hod/department'
      path: '/hod/department'
      fullPath: '/hod/department'
      preLoaderRoute: typeof HodDepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/notifications': {
      id: '/hod/notifications'
      path: '/hod/notifications'
      fullPath: '/hod/notifications'
      preLoaderRoute: typeof HodNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/passes': {
      id: '/hod/passes'
      path: '/hod/passes'
      fullPath: '/hod/passes'
      preLoaderRoute: typeof HodPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/safety-analytics': {
      id: '/hod/safety-analytics'
      path: '/hod/safety-analytics'
      fullPath: '/hod/safety-analytics'
      preLoaderRoute: typeof HodSafetyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/safety-prevention': {
      id: '/hod/safety-prevention'
      path: '/hod/safety-prevention'
      fullPath: '/hod/safety-prevention'
      preLoaderRoute: typeof HodSafetyPreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/settings': {
      id: '/hod/settings'
      path: '/hod/settings'
      fullPath: '/hod/settings'
      preLoaderRoute: typeof HodSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/students': {
      id: '/hod/students'
      path: '/hod/students'
      fullPath: '/hod/students'
      preLoaderRoute: typeof HodStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/timetable': {
      id: '/hod/timetable'
      path: '/hod/timetable'
      fullPath: '/hod/timetable'
      preLoaderRoute: typeof HodTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/violations': {
      id: '/hod/violations'
      path: '/hod/violations'
      fullPath: '/hod/violations'
      preLoaderRoute: typeof HodViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/check': {
      id: '/security/check'
      path: '/security/check'
      fullPath: '/security/check'
      preLoaderRoute: typeof SecurityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/dashboard': {
      id: '/security/dashboard'
      path: '/security/dashboard'
      fullPath: '/security/dashboard'
      preLoaderRoute: typeof SecurityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/incidents': {
      id: '/security/incidents'
      path: '/security/incidents'
      fullPath: '/security/incidents'
      preLoaderRoute: typeof SecurityIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/notifications': {
      id: '/security/notifications'
      path: '/security/notifications'
      fullPath: '/security/notifications'
      preLoaderRoute: typeof SecurityNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/passes': {
      id: '/security/passes'
      path: '/security/passes'
      fullPath: '/security/passes'
      preLoaderRoute: typeof SecurityPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/profile': {
      id: '/security/profile'
      path: '/security/profile'
      fullPath: '/security/profile'
      preLoaderRoute: typeof SecurityProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/reports': {
      id: '/security/reports'
      path: '/security/reports'
      fullPath: '/security/reports'
      preLoaderRoute: typeof SecurityReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/settings': {
      id: '/security/settings'
      path: '/security/settings'
      fullPath: '/security/settings'
      preLoaderRoute: typeof SecuritySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/timetable': {
      id: '/security/timetable'
      path: '/security/timetable'
      fullPath: '/security/timetable'
      preLoaderRoute: typeof SecurityTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/explanations': {
      id: '/student/explanations'
      path: '/student/explanations'
      fullPath: '/student/explanations'
      preLoaderRoute: typeof StudentExplanationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/passes': {
      id: '/student/passes'
      path: '/student/passes'
      fullPath: '/student/passes'
      preLoaderRoute: typeof StudentPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/student/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/student/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/violations': {
      id: '/student/violations'
      path: '/student/violations'
      fullPath: '/student/violations'
      preLoaderRoute: typeof StudentViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/$reportId': {
      id: '/admin/reports/$reportId'
      path: '/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminReportsReportIdRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/hod/cases/$reportId': {
      id: '/hod/cases/$reportId'
      path: '/$reportId'
      fullPath: '/hod/cases/$reportId'
      preLoaderRoute: typeof HodCasesReportIdRouteImport
      parentRoute: typeof HodCasesRoute
    }
  }
}

interface AdminReportsRouteChildren {
  AdminReportsReportIdRoute: typeof AdminReportsReportIdRoute
}

const AdminReportsRouteChildren: AdminReportsRouteChildren = {
  AdminReportsReportIdRoute: AdminReportsReportIdRoute,
}

const AdminReportsRouteWithChildren = AdminReportsRoute._addFileChildren(
  AdminReportsRouteChildren,
)

interface HodCasesRouteChildren {
  HodCasesReportIdRoute: typeof HodCasesReportIdRoute
}

const HodCasesRouteChildren: HodCasesRouteChildren = {
  HodCasesReportIdRoute: HodCasesReportIdRoute,
}

const HodCasesRouteWithChildren = HodCasesRoute._addFileChildren(
  HodCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckRoute: CheckRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TimetableRoute: TimetableRoute,
  ViolationsRoute: ViolationsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEmergencyRoute: AdminEmergencyRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminMovementPassesRoute: AdminMovementPassesRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminReportsRoute: AdminReportsRouteWithChildren,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSafetyAnalyticsRoute: AdminSafetyAnalyticsRoute,
  AdminSafetyPreventionRoute: AdminSafetyPreventionRoute,
  AdminSafetyReportsRoute: AdminSafetyReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminViolationsRoute: AdminViolationsRoute,
  FacultyCheckRoute: FacultyCheckRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyNotificationsRoute: FacultyNotificationsRoute,
  FacultyPassesRoute: FacultyPassesRoute,
  FacultyReportsRoute: FacultyReportsRoute,
  FacultySettingsRoute: FacultySettingsRoute,
  FacultyTimetableRoute: FacultyTimetableRoute,
  HodCasesRoute: HodCasesRouteWithChildren,
  HodDashboardRoute: HodDashboardRoute,
  HodDepartmentRoute: HodDepartmentRoute,
  HodNotificationsRoute: HodNotificationsRoute,
  HodPassesRoute: HodPassesRoute,
  HodSafetyAnalyticsRoute: HodSafetyAnalyticsRoute,
  HodSafetyPreventionRoute: HodSafetyPreventionRoute,
  HodSettingsRoute: HodSettingsRoute,
  HodStudentsRoute: HodStudentsRoute,
  HodTimetableRoute: HodTimetableRoute,
  HodViolationsRoute: HodViolationsRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  SecurityCheckRoute: SecurityCheckRoute,
  SecurityDashboardRoute: SecurityDashboardRoute,
  SecurityIncidentsRoute: SecurityIncidentsRoute,
  SecurityNotificationsRoute: SecurityNotificationsRoute,
  SecurityPassesRoute: SecurityPassesRoute,
  SecurityProfileRoute: SecurityProfileRoute,
  SecurityReportsRoute: SecurityReportsRoute,
  SecuritySettingsRoute: SecuritySettingsRoute,
  SecurityTimetableRoute: SecurityTimetableRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExplanationsRoute: StudentExplanationsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentPassesRoute: StudentPassesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentViolationsRoute: StudentViolationsRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
